version: "3.8"

services:

  # Esse é o banco de dados que a aplicação vai usar
  database:
    image: mariadb:10.10
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: rootpwd
      MARIADB_USER: mariadbuser
      MARIADB_PASSWORD: mariadbpwd
    healthcheck:
      test: "mysql -uroot -prootpwd mysql -e 'select 1'"
      start_period: 5s
      interval: 1s
      timeout: 5s
      retries: 10

  # Essa é a imagem docker responsável por executar os scripts SQL no banco de dados
  # Ela usa uma ferramenta chamada Flyway
  # O Flyway cria uma tabela no banco chamada flyway_schema_history em que controla todas as migrações (scripts sql)
  # aplicadas no banco, para que elas não sejam executadas novamente quando a imagem rodar
  database-migrations:
    build:
      # Se refere à pasta "database" na raiz do projeto, onde estão os SQLs
      context: database
    container_name: database-migrations
    environment:
      - FLYWAY_SCHEMAS=procjson
      - FLYWAY_DEFAULT_SCHEMA=procjson
      - FLYWAY_URL=jdbc:mariadb://database:3306?autoReconnect=true&useSSL=false
      - FLYWAY_USER=root
      - FLYWAY_PASSWORD=rootpwd
    command:
      # Exibe o estado do banco de dados antes das migrações
      - info
      # Corrige alguma migração que esteja com o checksum diferente do que está na tabela flyway_schema_history
      - repair
      # Aplica as migrações (os scripts sql) no banco de dados
      - migrate
      # Exibe o estado do banco depois das migrações
      - info
    depends_on:
      database:
        condition: service_healthy

  # Serviço Kafka
  kafka:
    image: moeenz/docker-kafka-kraft:latest
    restart: always
    ports:
      - "9093:9093"
    environment:
      - KRAFT_CONTAINER_HOST_NAME=kafka
      - KRAFT_CREATE_TOPICS=topic-a,topic-b,topic-c
      - KRAFT_PARTITIONS_PER_TOPIC=3


  # Kafka Producer
  kafka-producer:
    build:
      context: producer  # Diretório onde está o Dockerfile do Kafka Producer
    container_name: producer
    depends_on:
      - kafka
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093

  camel-consumer:
    build:
      context: consumer
    container_name: consumer
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/procfiles
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9093
    depends_on:
      database:
        condition: service_healthy
      database-migrations:
        condition: service_completed_successfully
